# Generated by Django 5.1.1 on 2024-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photosessions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="thumbnails/"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="photos/"),
        ),
    ]
