# Generated by Django 5.1.1 on 2024-09-30 12:38

import photosessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photosessions", "0002_remove_photo_uploaded_at_photo_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, upload_to=photosessions.models.get_thumbnail_path
            ),
        ),
    ]
