# Generated by Django 5.1.1 on 2024-09-30 12:48

import photosessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photosessions", "0003_alter_photo_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to=photosessions.models.get_photo_path),
        ),
    ]
